### ISSUE TITLE
done connecting, where to go from here, i.e. how to start game?

### ISSUE THREAD

**Issue by smixxer** [rcsoccersim/manual#122]
Hi,
I've successfully implemented a couple of "teams", in Java, each consisting of 11 UDP clients, which can do the "init" piece, as shown in the picture below:
![Schermata da 2022-04-01 07-58-39](https://user-images.githubusercontent.com/102723862/161205213-53696062-e8de-4bf4-8531-1d8f10872fe4.png)

But then, how to start the match, maybe with "Referee --> Kick Off"?

That way, I get these messages, not documented in the manual:
```
(hear 300 referee play_on)
(hear 300 referee drop_ball)
```

![Schermata da 2022-04-01 08-11-12](https://user-images.githubusercontent.com/102723862/161205372-6e5695c7-ba9f-47ce-b58c-188fb45afead.png)

Thanks for you patience.
Regards, smixxer.

**Comment by hidehisaakiyama** [comment]
> But then, how to start the match, maybe with "Referee --> Kick Off"?

Yes, it's a way to start the game manually.

Regarding the message from the referee, please see the following section:
https://rcsoccersim.readthedocs.io/en/latest/soccerserver.html#play-modes-and-referee-messages

Unfortunately, we still need to improve the user's manual.
If you find the lack of content, please report it as an issue.

And again, GitHub issue (here) is not a help forum.
If you need help, please consider joining the discord server, or please use the 'Discussion' feature of GitHub.
