### ISSUE TITLE
Client: Protocols

### ISSUE THREAD

**Issue by hidehisaakiyama** [rcsoccersim/manual#13]

**Comment by bandreghetti** [comment]
Is this documentation being transcribed from an existing document? If so, I'd be more than happy to contribute! I've been looking for v15 protocol API but I can't find a complete document anywhere.

**Comment by herodrigues** [comment]
Yes. It's been transcribed from the old Tex documentation.

**Comment by hidehisaakiyama** [comment]
Maintaners are working to transcribe old documents and trying to add new ones for the latest specifications. It may take a time due to the problem of human resources. Contributions are always welcome! Thanks.

**Comment by bandreghetti** [comment]
Where can I find the old Tex documentation? Is it this one https://rcsoccersim.github.io/rcssserver-manual-20030211.pdf or is there a newer one? Thanks!

**Comment by herodrigues** [comment]
Yes, but the TeX files are here: https://sourceforge.net/p/sserver/code/HEAD/tree/rcss/trunk/manual/
