### ISSUE TITLE
Document see message's one letter parameters

### ISSUE THREAD

**Issue by gikari** [rcsoccersim/manual#43]
Currently the documentation about `see` message contains the following description:
```
(see Time ObjInfo+)
Time ::= simulation cycle of rcssserver
ObjInfo ::=
(ObjName Distance Diretion DistChange DirChange BodyFacingDir HeadFacingDir [PointDir] [t] [k]])
| (ObjName Distance Diretion DistChange DirChange [PointDir] [t] [k]])
| (ObjName Distance Diretion)
| (ObjName Diretion)
ObjName ::= (p [“TeamName” [UniformNumber [goalie]]])
| (b)
| (g {l|r})
| (f c)
| (f {l|c|r} {t|b})
| (f p {l|r} {t|c|b})
| (f g {l|r} {t|b})
| (f {l|r|t|b} 0)
| (f {t|b} {l|r} {10|20|30|40|50})
| (f {l|r} {t|b} {10|20|30})
| (l {l|r|t|b} 0)
| (P)
| (B)
| (G)
| (F)
Distance ::= positive real number
Direction ::= -180 ~ 180 degrees
DistChange ::= real number
DirChange ::= real number
BodyFacingDir ::= -180 ~ 180 degrees
HeadFacingDir ::= -180 ~ 180 degrees
PointDir ::= -180 ~ 180 degrees
TeamName ::= string
UniformNumber ::= 1 ~ 11
```

It's unclear what the `[t]` and `[k]` in the `ObjInfo` part mean, because the names are just letters. Less unclear, but still not clear enough, are the `ObjName` variations. I suppose `(p ...)` is for player and other letters are related to flags, lines and goals:

![Screenshot_20200624_213303](https://user-images.githubusercontent.com/14205339/85613197-26eaa080-b649-11ea-9baa-4e91fc9b2508.png)

But what about capital letters at the end (`(P)` `(B)` `(G)` `(F)`)? The `(b)`?

I think it would be better to describe these parameters in place, preferably with the above image so that the reader can better understand the context.

**Comment by mattyoung101** [comment]
I just had to deal with this while testing my agents' message parser against a real team (HELIOS), so I can answer a few questions.

By looking into the sources for librcsc, the most common library in RoboCup 2D, it seems as though the (P), (B), (G), etc, flags are "behind". I assume that means behind the agent but I'm not sure. So far, it seems they contain no useful info so you can just discard them.

The different variations in ObjInfo are indeed for different objects. `p` is for player. Be warned that the server may send next to no info about the player, so your parser should accept missing team name, unum, etc.

I have no idea what `t` or `k` are. There's no documentation on this in the 2003 manual or the website. I assume they have something to do with the new `attentionto` command, but you'd have to look into the server sources to find out. Currently, my parser just recognises and then discards it.

Either way, I think more documentation would be very helpful. I've had to look at the server and librcsc sources multiple times to figure out what's going on. The website docs are missing many sections, I'm willing to help out (but I don't know much).

**Comment by hidehisaakiyama** [comment]
I'm sorry. Although the community recognizes the documentation is one of the most important tasks, it is still imperfect due to the lack of human resources.
You can find the description of capital letters in section 4.3.2 of the manual,

> The player can also “see” an object if it’s within server::visible_distance meters of the player. If the objects is within this distance but not in the view cone then the player can know only the type of the object (ball, player, goal or flag), but not the exact name of the object. Moreover, in this case, the capitalized name, that is “B”, “P”, “G” and “F”, is used as the name of the object rather than “b”, “p”, “g” and “f”.


[t] and [k] have not been described in the manual yet. You can find the short description in rcssserver's NEWS file:

In the part of [8.04],
>  When players can see another players team, they can also see if that player
>   is tackling via a `t' flag as follows:
> 
>   `((p "<TEAMNAME>" <UNUM>) <DIST> <DIR> <DISTCHG> <DIRCHG>
>                             <BDIR> <HDIR> [<POINTDIR>] [t])'
> 
>   `((p "<TEAMNAME>") <DIST> <DIR> [<POINTDIR>] [t])'

In the part of [13.0.0],
> - Version 13+ players and coaches can see players' kicking state.
> 
>       When players can see another players team, they can also see if
>       that player is kicking via a `k' flag as follows:
> 
>         `((p "<TEAMNAME>" <UNUM>) <DIST> <DIR> <DISTCHG> <DIRCHG>
>                                  <BDIR> <HDIR> [<POINTDIR>] [{t|k}])'
> 
>         `((p "<TEAMNAME>") <DIST> <DIR> [<POINTDIR>] [{t|k}])'
> 
>       Coach visuals now can indicate if a player is kicking via a `k'
>       flag as follows:
> 
>         `((p "<TEAMNAME>" <UNUM>) <X> <Y> <VEL_X> <VEL_Y> <ANGLE>
>                                   <NECK_ANGLE> [<ARM_DIR>] [{t|k}])'
> 
>       If an observed player is tackling, the kicking flag is always
>       overwritten by the tackle flag.
> 
>       Please note that the kicking state can be seen within one cycle
>       just after kicking.
>

**Comment by mattyoung101** [comment]
Thanks so much for the clarification! I'll make a pull request to add `t` and `k` descriptions to the see model section of the manual.
